### ISSUE TITLE
What will it take for us to update to javacc21

### ISSUE THREAD

**Issue by nickl-** [tulipcc/ph-javacc-maven-plugin#18]
Do you have some time for me please?

I know, I know, this is already asking for a lot, so I will promise to be totally honest and transparent from the get go. I am knocking on your door in the hope that it might save me some time. I will in turn do my utmost not to waste any of your time and assist wherever I can.

 Not that I am very caught up with the goings on, haven't so much as given `javacc` a second thought for the best part of 4 years. Recently updated the `ph` [plugin to the latest version](https://github.com/beanshell/beanshell), and aside from a cosmetic name change affecting custom code everything went smoothly, thank you in the most part for that. Unsurprisingly all the issues from 4 years ago still remain...

We were contacted by @revusky https://github.com/beanshell/beanshell/issues/591 a while back, will nudge him closer if the ping misses, I am sure he will also be keen to see plugin support going. So what is [javacc21](https://github.com/javacc21/javacc21/)? You will find lots on the politics and history, which makes for an interesting read, but for expediency here's the ;tldr.

Fork made in 2009, politely renamed FreeCC... ten years later the changes made back then is still the most updated revision of the original SUN source available. Taking a more aggressive stance, javacc 2021 now considers itself the official and actively maintained project, not a fork.

Good news for JAVA is the [updated and current lexer example](https://github.com/javacc21/javacc21/tree/master/examples/java) (v19.0.0) and the updates are a clear improvement to the legibility of the grammar. Whether this is good news for the 20 year legacy in the BeanShell source remains to be seen, but I am sure you will agree that any progress is a welcome sight.

From what I can tell these are the shortcuts to the relevant documentation:

1. [Getting started](https://doku.javacc.com/doku.php?id=start_hacking)
2. [Settings and configuration](https://doku.javacc.com/doku.php?id=new_settings_in_javacc_21)
3. [Deprecated configuration](https://doku.javacc.com/doku.php?id=deprecated_settings)
4. [Key Differences](https://doku.javacc.com/doku.php?id=key_differences) - careful from here may lead to distraction

 How you can help:

1. Your opinion please
If you only have the very most limited time to share, please give the project a quick once over and share your initial thoughts. Your expert opinion and experience for at least staying up to date with upstream releases will be highly regarded. This will save me loads of time but most importantly it clears up head space to focus on the issue backlog and release road map for BeanShell 3.0. knowing that more capable hands are on the task. I cannot ask for anything else and will be forever grateful for this favour.  But should you feel inspired and keen to also dive in at 99 to see what else can be accomplished in '22, here are some more suggestions.
2. Design the plugin update to javacc21
Can you see a path and enough similarities to add javacc as an additional configurable parser to the existing `ph` plugin or do we start from scratch. Even just knowing whether they are compatible or not will pay dividents and someone else might get inspired to pitch in. 
3.  Develop the maven plugin support for javacc21
I am sure we are not alone, having a maven plugin to generate the AST will fit our current workflow and paves the way to javacc21 adoption.
4. Migrate custom BeanShell grammar to javacc21's plain JAVA lexer
BeanShell's no 1 goal is to be JAVA compatible and to be able to parse pure JAVA code and interpret it to work the same way JAVA does. The project does not aim to break the same way JAVA does, and the dynamic nature of a scripting engine allows us many privileges to enhance the developer's experience. Even though we make every effort to stay true to a natural evolution of JAVA even just the laxities from the rigid java syntax will most certainly break the parser. If you are keen to test drive the new grammar and get your hands dirty, the BeanShell project will be a legacy to your efforts.
5. Migrate existing BeanShell AST Node tree interpreter
Ultimately this will be the make or break challenge which will prove whether BeanShell adopt javacc21 or remain stuck with its legacy. Even though there is a whole ecosystem build around the parser to facilitate a complete programming language in its own right, a lot is still dependent on the existing nodes and their structure which is sure to be affected. But what better way to see how it all fits together. Besides you know every developer has to write at least one language in their lifetime. =)

I also know it is holiday and family time not everyone has the luxury and freedom to grind away at this moment, please don't feel obligated to answer the call immediately. Whatever time allows is much appreciated.

**Comment by phax** [comment]
Not interested - thank you :)

**Comment by nickl-** [comment]
> Not interested - thank you :)

Wow that was a quick response, you are on the ball. =)

Thank you for your consideration.

**Comment by revusky** [comment]
I dropped you an email at github@jigsoft.co.za 

Not 100% sure you got it. So I answer here as well. Please start a discussion at https://discuss.congocc.org/

**Comment by vlsi** [comment]
@nickl- , I have contacted Jonathan previously, and I even contributed to JavaCC21: https://github.com/javacc21/javacc21/pull/15
The PR was merged, however, later Jonathan went off rails when [I asked to clarify the license](https://github.com/javacc21/javacc21/pull/16), so all the contributions were reverted, and I stopped communication with javacc21.

Unfortunately, Jonathan's behaviour is toxic: https://github.com/javacc/javacc/discussions/227#discussioncomment-3099167. 

That is why I would refrain from communicating with javacc21 community even in the case javacc21 is technologically more advanced.
Jonathan contacted me this October, and unfortunately, the case is still the same.

So I would suggest you study the links in https://github.com/javacc/javacc/discussions/227#discussioncomment-3099167 before proceeding with javacc21.


---

>Unsurprisingly all the issues from 4 years ago still remain...

Would you mind which issues you mean?
Frankly speaking, I think tulipcc is pretty much fixable/releasable, so if you have pressing issues, try voicing them.
If you have something like "oh, let's support Java 20 grammar", then, well, it might be a bit challenging.

**Comment by revusky** [comment]
Fellas,

You'll have to cut Vladimir some slack. He is especially deranged and disturbed now. This is because he just learned that his mama always wanted a boy.

His grandma also. However, that is not additional information In Vladimir's case, because his mother is also his grandmother.

**Comment by nickl-** [comment]
Lets not hijack @phax 's project for this discussion, this issue was meant as an honest request to get the plugin we are currently using updated to javacc21, and the maintainer clearly stated they are not interested. Issue closed.

There is already a javacc21 thread on the BeanShell project https://github.com/beanshell/beanshell/issues/591 which can be used to air out old laundry instead, I will take no offense.

Albeit related, this issue had nothing to do with the javacc21 build process or lack of maven artifacts. In fact a lesson can be learnt from the `ph` plugin, it has the javacc parser included in the artifact. This is the beauty of opensource, if you don't like what the other project is doing, just fork it. The project that is actively maintained and caters best to the end users requirements is the one that will be used (if logic and common sense prevails which is not guaranteed). So enough said here on that lets take it to https://github.com/beanshell/beanshell/issues/591 if feeling compelled to respond.

A final word (from me at least) on this issue, so that others also interested in this topic may benefit from the work I already did. Managed to accomplish the requirement of generating javacc21 based AST as part of the maven build process with the use of two plugins: [com.googlecode.maven-download-plugin/download-maven-plugin](https://github.com/maven-download-plugin/maven-download-plugin) and [org.codehaus.mojo/exec-maven-plugin](https://www.mojohaus.org/exec-maven-plugin/)

Here is the plugin configuration I used:

```xml
      <plugin>
        <groupId>com.googlecode.maven-download-plugin</groupId>
        <artifactId>download-maven-plugin</artifactId>
        <version>1.6.8</version>
        <executions>
          <execution>
            <id>install-javacc21</id>
              <phase>generate-sources</phase>
            <goals>
              <goal>wget</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <outputDirectory>${user.home}/.m2/</outputDirectory>
          <url>https://javacc.com/download/javacc-full.jar</url>
          <unpack>false</unpack>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>generate-ast</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <configuration>
              <executable>java</executable>
              <commandlineArgs>-jar ${user.home}/.m2/javacc-full.jar -n -q -d ../../target/generate-sources -jdk18 examples/java/Java.javacc</commandlineArgs>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

1. Will download the javacc21 jar file from official release location (at the time of this writing) to the `.m2` folder in the user's home directory. Which allows for clean builds not having to downloading the javacc21 dependency again.
2. Will execute the jar file on the examples java grammar and generate source to the `target/generate-sources` directory, as would be expected for maven workflows.

**Comment by vlsi** [comment]
@nickl- , javacc21 is off-topic for tulipcc, and ph-javacc-maven-plugin.
